# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('passwrod', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=32)),
                ('marjor', models.CharField(max_length=32)),
                ('counte', models.IntegerField()),
            ],
        ),
    ]
