# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-27 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0002_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='passwrod',
            new_name='password',
        ),
    ]
