# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-27 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0003_auto_20200727_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('email',)]),
        ),
    ]
