# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-28 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0004_auto_20200727_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='marjor',
            new_name='major',
        ),
    ]
