# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0005_auto_20200729_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=32)),
                ('context', models.CharField(max_length=1024)),
            ],
        ),
    ]
