# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-31 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0006_article'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together=set([('email', 'title')]),
        ),
    ]
