# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-07-31 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0007_auto_20200731_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='counte',
            new_name='counter',
        ),
    ]
