# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-08-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0008_auto_20200731_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.CharField(max_length=10240),
        ),
    ]
