# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-08-02 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0010_auto_20200802_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='context',
            field=models.CharField(max_length=10240),
        ),
    ]
